import type { HiddenObjectDefinition, SceneDefinition, SceneLayer, SceneLookAlike, SceneStation, TargetId } from "@/games/hidden-objects/hidden-objects-scene";

/**
 * Estúdio do Explorador — Game 03's first room (GAME03-SKELETON-01, GAME03-EXPERIENCE-02),
 * as data. Moved here unchanged by GAME03-MULTISCENE-03 (3200×1600 su, a pool of
 * eighteen, art kit v1). GAME03-CALIBRATION-02A made it harder to search without
 * moving anything already there: art kit v2 tucks five more objects into the room
 * and paints eleven more look-alikes, every object carries a clue bank and the
 * audit's measurements of it (`measured`, from the kit's fairness.json).
 * tools/assets/create_hidden_objects_scene.mjs paints every target exactly where
 * its `region` says, and reads this module to do it.
 */

/** Which room a session explored (the result records it; results saved before it existed are all this room). */
export const SCENE_ID = "explorer-studio";

export const SCENE_WIDTH = 3200;
export const SCENE_HEIGHT = 1600;

export const SCENE_STATIONS: readonly SceneStation[] = [
  {
    id: "janela",
    label: "Janela",
    center: { x: 620, y: 860 },
    span: { x0: 0, x1: 1060 },
    hintPhrase: "perto da janela",
  },
  {
    id: "mesa",
    label: "Mesa",
    center: { x: 1600, y: 900 },
    span: { x0: 1060, x1: 2140 },
    hintPhrase: "na mesa",
  },
  {
    id: "estante",
    label: "Estante",
    center: { x: 2620, y: 760 },
    span: { x0: 2140, x1: SCENE_WIDTH },
    hintPhrase: "na estante",
  },
];

/**
 * The pool: every object a round may ask for, each painted exactly once and
 * always in the room — a round lists a handful (DIFFICULTY_PRESETS), the rest
 * stay scenery and distractors, never marked as candidates.
 * GAME03-EXPERIENCE-02 moved the lanterna to B (dimmer, behind books, beside a
 * look-alike) and the câmera to C (darker, half behind a leaning book), then
 * grew the pool from the skeleton's ten to eighteen: six things the room
 * already showed (xícara, pena, borboleta, chapéu, bolsa, globo — the same
 * paint, now with a region) and two new ones by the window (guarda-chuva,
 * gaiola), so every station holds every tier. GAME03-CALIBRATION-02A added five
 * objects the room hides in plain materials — a snail on the wainscot, a spinning
 * top on the rug's edge, scissors under the map, a pine cone on the wall shelf, a
 * harmonica on the book pile (twenty-three: A6 · B7 · C10). Positions are
 * authored, never drawn at random: only which of them a round lists is.
 */
export const HIDDEN_OBJECTS: readonly HiddenObjectDefinition[] = [
  {
    id: "ampulheta",
    label: "Ampulheta",
    accessibleLabel: "Ampulheta",
    clues: [
      { level: "direct", text: "Marca o tempo com areia que escorre." },
      { level: "associative", text: "Vira de ponta-cabeça para contar de novo." },
      { level: "associative", text: "Dois bojos de vidro unidos por uma cintura." },
      { level: "indirect", text: "Quando o último grão cai, a espera acabou." },
      { level: "indirect", text: "Num jogo de tabuleiro, avisa que a vez acabou." },
    ],
    tier: "A",
    station: "janela",
    region: { kind: "rect", x: 742, y: 952, w: 116, h: 222 },
    measured: { visible: 0.956, edge: 1.77, clutter: 0.15 },
    hintRegion: "na mesinha junto à janela",
    hintDirection: "mais abaixo, ao lado da poltrona",
    hintContext: "perto de onde alguém se senta para ler",
  },
  {
    id: "binoculo",
    label: "Binóculo",
    accessibleLabel: "Binóculo",
    clues: [
      { level: "direct", text: "Dois tubos com lentes para ver de longe." },
      { level: "associative", text: "Aproxima o navio que ainda está no horizonte." },
      { level: "associative", text: "Vai no pescoço de quem observa pássaros." },
      { level: "indirect", text: "Na arquibancada, traz o jogador para perto." },
      { level: "indirect", text: "Com ele, a ave no alto da árvore vira detalhe." },
    ],
    tier: "B",
    station: "janela",
    region: { kind: "rect", x: 424, y: 930, w: 152, h: 78 },
    measured: { visible: 0.846, edge: 1.32, clutter: 0.157 },
    hintRegion: "no peitoril da janela",
    hintDirection: "na base da janela, do lado esquerdo",
    hintContext: "onde a luz da tarde entra, entre vasos e pedrinhas",
  },
  {
    id: "chave",
    label: "Chave antiga",
    accessibleLabel: "Chave antiga",
    clues: [
      { level: "direct", text: "Abre o que está trancado." },
      { level: "associative", text: "Gira dentro da fechadura." },
      { level: "associative", text: "Tem dentes, mas nunca mordeu ninguém." },
      { level: "indirect", text: "Sem ela, a porta fica fechada para sempre." },
      { level: "indirect", text: "Quem a perde fica do lado de fora de casa." },
    ],
    tier: "C",
    station: "janela",
    region: { kind: "rect", x: 452, y: 1246, w: 132, h: 56 },
    measured: { visible: 0.71, edge: 1.67, clutter: 0.135 },
    hintRegion: "sobre o baú",
    hintDirection: "mais embaixo, perto do chão",
    hintContext: "em cima de algo que guarda coisas fechadas",
  },
  {
    id: "guarda-chuva",
    label: "Guarda-chuva",
    accessibleLabel: "Guarda-chuva",
    clues: [
      { level: "direct", text: "Abre-se para proteger da água do céu." },
      { level: "associative", text: "Fechado num canto, espera o tempo virar." },
      { level: "associative", text: "Tem varetas, pano esticado e um cabo curvo." },
      { level: "indirect", text: "Nuvens carregadas? Melhor levá-lo ao sair." },
      { level: "indirect", text: "Numa garoa fina, salva o penteado." },
    ],
    tier: "A",
    station: "janela",
    region: { kind: "rect", x: 986, y: 930, w: 64, h: 258 },
    measured: { visible: 0.965, edge: 1.44, clutter: 0.136 },
    hintRegion: "encostado na parede, entre a janela e a mesa",
    hintDirection: "mais embaixo, à direita da janela",
    hintContext: "encostado num canto, perto da mesa redonda",
  },
  {
    id: "gaiola",
    label: "Gaiola",
    accessibleLabel: "Gaiola de passarinho",
    clues: [
      { level: "direct", text: "Casinha com grades para um passarinho." },
      { level: "associative", text: "Tem um poleiro, um bebedouro e uma portinha." },
      { level: "associative", text: "Pendurada, ainda espera um canário." },
      { level: "indirect", text: "Ali dentro, alguém cantava todas as manhãs." },
      { level: "indirect", text: "Um alpiste esquecido lembra quem morava ali." },
    ],
    tier: "C",
    station: "janela",
    region: { kind: "rect", x: 960, y: 446, w: 76, h: 142 },
    measured: { visible: 0.934, edge: 1.53, clutter: 0.047 },
    hintRegion: "pendurada na parede, à direita da janela",
    hintDirection: "no alto, entre a janela e os quadros",
    hintContext: "presa num gancho, perto de uma planta pendurada",
  },
  {
    id: "caracol",
    label: "Caracol",
    accessibleLabel: "Caracol",
    clues: [
      { level: "direct", text: "Bichinho lento que carrega a casa nas costas." },
      { level: "associative", text: "Deixa um rastro brilhante por onde passa." },
      { level: "associative", text: "Tem antenas com olhinhos na ponta." },
      { level: "indirect", text: "Depois do temporal, aparece no muro sem pressa." },
      { level: "indirect", text: "Leva o dia todo para atravessar o jardim." },
    ],
    tier: "C",
    station: "janela",
    region: { kind: "rect", x: 598, y: 1052, w: 88, h: 60 },
    measured: { visible: 0.794, edge: 2.02, clutter: 0.201 },
    hintRegion: "no lambri, logo abaixo do peitoril",
    hintDirection: "embaixo da janela, perto das plantas do peitoril",
    hintContext: "subindo devagar pela madeira da parede",
  },
  {
    id: "piao",
    label: "Pião",
    accessibleLabel: "Pião de madeira",
    clues: [
      { level: "direct", text: "Brinquedo que gira na ponta depois de lançado." },
      { level: "associative", text: "Enrola-se a fieira e lança-se no chão." },
      { level: "associative", text: "Dança sozinho até ficar tonto e cair." },
      { level: "indirect", text: "Na roda, ganha quem o deixa de pé mais tempo." },
      { level: "indirect", text: "Um barbante, um puxão e começa a festa no chão." },
    ],
    tier: "C",
    station: "janela",
    region: { kind: "rect", x: 698, y: 1326, w: 82, h: 74 },
    measured: { visible: 0.977, edge: 2.28, clutter: 0.144 },
    hintRegion: "na beirada do tapete, junto do baú",
    hintDirection: "no chão, entre o baú e a mesinha",
    hintContext: "no chão, perto de onde o tapete começa",
  },
  {
    id: "lupa",
    label: "Lupa",
    accessibleLabel: "Lupa",
    clues: [
      { level: "direct", text: "Amplia pequenos detalhes." },
      { level: "associative", text: "Um detetive famoso nunca saía sem ela." },
      { level: "associative", text: "Um aro com cabo e um vidro que engorda letras." },
      { level: "indirect", text: "Com ela, a formiga parece um gigante." },
      { level: "indirect", text: "Ajuda a ler a bula de letra miudinha." },
    ],
    tier: "A",
    station: "mesa",
    region: { kind: "circle", cx: 1760, cy: 1040, r: 92 },
    measured: { visible: 0.998, edge: 1.75, clutter: 0.153 },
    hintRegion: "sobre o mapa",
    hintDirection: "no meio da mesa, um pouco à direita",
    hintContext: "sobre um papel cheio de caminhos",
  },
  {
    id: "bussola",
    label: "Bússola",
    accessibleLabel: "Bússola",
    clues: [
      { level: "direct", text: "Aponta sempre para o norte." },
      { level: "associative", text: "Uma agulha que não costura, só orienta." },
      { level: "associative", text: "Os marinheiros a seguiam antes do GPS." },
      { level: "indirect", text: "Perdido na mata, você a consultaria primeiro." },
      { level: "indirect", text: "Um ímã escondido decide para onde ir." },
    ],
    tier: "B",
    station: "mesa",
    region: { kind: "circle", cx: 1540, cy: 1160, r: 66 },
    measured: { visible: 0.88, edge: 1.97, clutter: 0.209 },
    hintRegion: "na borda do mapa",
    hintDirection: "na frente da mesa, perto da beirada",
    hintContext: "entre um livro aberto e um mapa",
  },
  {
    id: "relogio",
    label: "Relógio",
    accessibleLabel: "Relógio de bolso",
    clues: [
      { level: "direct", text: "Mostra as horas e cabe no bolso." },
      { level: "associative", text: "Tique-taque preso a uma corrente." },
      { level: "associative", text: "Dava-se corda nele todo dia para não parar." },
      { level: "indirect", text: "Quando ele para, ninguém sabe se está atrasado." },
      { level: "indirect", text: "Herança de família que se abre com um clique." },
    ],
    tier: "C",
    station: "mesa",
    region: { kind: "circle", cx: 1330, cy: 1178, r: 48 },
    measured: { visible: 0.859, edge: 1.62, clutter: 0.236 },
    hintRegion: "perto do livro aberto",
    hintDirection: "no lado esquerdo da mesa, bem na frente",
    hintContext: "junto de moedas, preso a uma corrente",
  },
  {
    id: "xicara",
    label: "Xícara",
    accessibleLabel: "Xícara de chá",
    clues: [
      { level: "direct", text: "Leva o chá quentinho até a boca." },
      { level: "associative", text: "Tem asa, pires e cheiro de café." },
      { level: "associative", text: "Fica sobre um pires, soltando vapor." },
      { level: "indirect", text: "Às cinco da tarde, os ingleses a enchem." },
      { level: "indirect", text: "Mindinho levantado, ela vai até os lábios." },
    ],
    tier: "C",
    station: "mesa",
    region: { kind: "rect", x: 1380, y: 950, w: 100, h: 60 },
    measured: { visible: 0.538, edge: 1.75, clutter: 0.191 },
    hintRegion: "atrás do livro aberto",
    hintDirection: "no fundo da mesa, à esquerda do mapa",
    hintContext: "soltando vapor, perto de páginas abertas",
  },
  {
    id: "pena",
    label: "Pena",
    accessibleLabel: "Pena de escrever",
    clues: [
      { level: "direct", text: "Escrevia molhando a ponta na tinta." },
      { level: "associative", text: "Antes da tinta, ela esteve num ganso." },
      { level: "associative", text: "Ganhava ponta nova com um canivete." },
      { level: "indirect", text: "Antes de assinar cartas, ela voava." },
      { level: "indirect", text: "Um poeta antigo gastava várias por poema." },
    ],
    tier: "B",
    station: "mesa",
    region: { kind: "rect", x: 1994, y: 896, w: 82, h: 170 },
    measured: { visible: 0.999, edge: 2.93, clutter: 0.126 },
    hintRegion: "na ponta direita da mesa",
    hintDirection: "na beirada direita da mesa, junto da parede",
    hintContext: "de pé num frasco escuro, na beira da mesa",
  },
  {
    id: "borboleta",
    label: "Borboleta",
    accessibleLabel: "Borboleta emoldurada",
    clues: [
      { level: "direct", text: "Tem asas coloridas, mas não voa mais." },
      { level: "associative", text: "Já foi lagarta antes de ir para o quadro." },
      { level: "associative", text: "Presa por um alfinete, atrás do vidro." },
      { level: "indirect", text: "Saiu de um casulo e hoje enfeita a parede." },
      { level: "indirect", text: "Num jardim, ela iria de flor em flor." },
    ],
    tier: "A",
    station: "mesa",
    region: { kind: "rect", x: 1932, y: 318, w: 104, h: 124 },
    measured: { visible: 1, edge: 1.33, clutter: 0.08 },
    hintRegion: "no quadrinho mais alto da parede",
    hintDirection: "no alto da parede, à direita dos quadros grandes",
    hintContext: "atrás de um vidro, entre molduras douradas",
  },
  {
    id: "chapeu",
    label: "Chapéu",
    accessibleLabel: "Chapéu de explorador",
    clues: [
      { level: "direct", text: "Vai na cabeça de quem viaja." },
      { level: "associative", text: "Aba larga contra o sol da expedição." },
      { level: "associative", text: "Tira-se em sinal de respeito." },
      { level: "indirect", text: "Num dia de sol forte na trilha, protege a nuca." },
      { level: "indirect", text: "Um mágico tiraria um coelho de um parecido." },
    ],
    tier: "B",
    station: "mesa",
    region: { kind: "rect", x: 2066, y: 428, w: 124, h: 66 },
    measured: { visible: 1, edge: 1.91, clutter: 0.102 },
    hintRegion: "no cabideiro da parede",
    hintDirection: "na parede, logo antes da estante",
    hintContext: "pendurado num gancho de madeira, perto da estante",
  },
  {
    id: "tesoura",
    label: "Tesoura",
    accessibleLabel: "Tesoura",
    clues: [
      { level: "direct", text: "Corta com duas lâminas que se cruzam." },
      { level: "associative", text: "Dois anéis para os dedos e um bico afiado." },
      { level: "associative", text: "Faz pedaços de fita em festa de inauguração." },
      { level: "indirect", text: "Sem ela, o recorte do mapa sairia rasgado." },
      { level: "indirect", text: "O barbeiro a faz cantar perto da orelha." },
    ],
    tier: "C",
    station: "mesa",
    region: { kind: "rect", x: 1512, y: 952, w: 92, h: 60 },
    measured: { visible: 0.624, edge: 2.01, clutter: 0.188 },
    hintRegion: "atrás do livro aberto, na borda do mapa",
    hintDirection: "no fundo da mesa, logo acima do mapa",
    hintContext: "meio escondida pela borda de um papel cheio de caminhos",
  },
  {
    id: "pinha",
    label: "Pinha",
    accessibleLabel: "Pinha",
    clues: [
      { level: "direct", text: "Fruto de pinheiro, cheio de escamas." },
      { level: "associative", text: "Os pinhões moram entre as escamas dela." },
      { level: "associative", text: "Cai das árvores de Natal de verdade." },
      { level: "indirect", text: "A semente da festa junina cresce dentro dela." },
      { level: "indirect", text: "O esquilo daria tudo para levá-la para a toca." },
    ],
    tier: "B",
    station: "mesa",
    region: { kind: "rect", x: 1276, y: 614, w: 60, h: 84 },
    measured: { visible: 1, edge: 1.51, clutter: 0.135 },
    hintRegion: "na prateleira de parede, entre os potes e os livros",
    hintDirection: "na parede, acima da mesa, à esquerda",
    hintContext: "numa prateleira, entre um pote de louça e livros deitados",
  },
  {
    id: "barco",
    label: "Barco em miniatura",
    accessibleLabel: "Barco em miniatura",
    clues: [
      { level: "direct", text: "Viaja sobre a água, levado pelo vento." },
      { level: "associative", text: "Tem velas, mas nunca acendeu nenhuma." },
      { level: "associative", text: "Um capitão de bolso caberia no convés." },
      { level: "indirect", text: "Num dia de calmaria, ele não sairia do lugar." },
      { level: "indirect", text: "Montado peça por peça, nunca molhou o casco." },
    ],
    tier: "A",
    station: "estante",
    region: { kind: "rect", x: 2360, y: 615, w: 290, h: 215 },
    measured: { visible: 0.957, edge: 1.93, clutter: 0.181 },
    hintRegion: "na prateleira do meio",
    hintDirection: "no meio da estante, do lado esquerdo",
    hintContext: "entre livros, numa prateleira do meio",
  },
  {
    id: "lanterna",
    label: "Lanterna",
    accessibleLabel: "Lanterna",
    clues: [
      { level: "direct", text: "Leva a luz para onde você for." },
      { level: "associative", text: "Uma chaminha presa numa casinha de vidro." },
      { level: "associative", text: "Os mineiros a carregavam nos túneis." },
      { level: "indirect", text: "Numa noite sem lua, guiaria seus passos." },
      { level: "indirect", text: "Faltou energia? Ela resolve sem tomada." },
    ],
    tier: "B",
    station: "estante",
    region: { kind: "rect", x: 2780, y: 848, w: 126, h: 212 },
    measured: { visible: 0.749, edge: 1.54, clutter: 0.166 },
    hintRegion: "nas prateleiras de baixo",
    hintDirection: "na parte de baixo da estante, à direita",
    hintContext: "numa prateleira baixa, cercada de livros",
  },
  {
    id: "camera",
    label: "Câmera",
    accessibleLabel: "Câmera fotográfica antiga",
    clues: [
      { level: "direct", text: "Captura uma cena com um clique." },
      { level: "associative", text: "Prende o momento num filme, não na memória." },
      { level: "associative", text: "Diga xis para ela." },
      { level: "indirect", text: "O que ela via só aparecia depois de revelado." },
      { level: "indirect", text: "Os álbuns de família começam com ela." },
    ],
    tier: "C",
    station: "estante",
    region: { kind: "rect", x: 2720, y: 480, w: 166, h: 118 },
    measured: { visible: 0.836, edge: 2.99, clutter: 0.176 },
    hintRegion: "na segunda prateleira",
    hintDirection: "no alto da estante, do lado direito",
    hintContext: "numa prateleira cheia de livros, perto de potes de vidro",
  },
  {
    id: "estatueta",
    label: "Estatueta",
    accessibleLabel: "Estatueta",
    clues: [
      { level: "direct", text: "Uma pequena figura esculpida." },
      { level: "associative", text: "Feita em pedra ou gesso, imita uma pessoa." },
      { level: "associative", text: "Uma pessoa que nunca se mexe nem pisca." },
      { level: "indirect", text: "Num concurso, o vencedor leva uma parecida." },
      { level: "indirect", text: "Posa para sempre, sem nunca cansar." },
    ],
    tier: "C",
    station: "estante",
    region: { kind: "rect", x: 2615, y: 245, w: 84, h: 122 },
    measured: { visible: 0.753, edge: 2.93, clutter: 0.148 },
    hintRegion: "na prateleira mais alta",
    hintDirection: "bem no alto da estante",
    hintContext: "entre lombadas de livros, perto do teto",
  },
  {
    id: "globo",
    label: "Globo",
    accessibleLabel: "Globo terrestre",
    clues: [
      { level: "direct", text: "Mostra o mundo inteiro numa bola." },
      { level: "associative", text: "Gira num eixo inclinado, com mares e países." },
      { level: "associative", text: "Na aula de geografia, todos giravam ele." },
      { level: "indirect", text: "Gire e aponte: lá será a próxima viagem." },
      { level: "indirect", text: "Onde fica o Brasil? Ele responde sem tela." },
    ],
    tier: "A",
    station: "estante",
    region: { kind: "circle", cx: 2200, cy: 990, r: 96 },
    measured: { visible: 0.997, edge: 1.7, clutter: 0.129 },
    hintRegion: "entre a mesa e a estante",
    hintDirection: "embaixo, na beirada esquerda da estante",
    hintContext: "num pé alto, ao lado da mesa redonda",
  },
  {
    id: "bolsa",
    label: "Bolsa de couro",
    accessibleLabel: "Bolsa de couro",
    clues: [
      { level: "direct", text: "Leva as coisas pendurada no ombro." },
      { level: "associative", text: "Tem uma tira comprida e uma aba que fecha." },
      { level: "associative", text: "O explorador leva nela o mapa e o lanche." },
      { level: "indirect", text: "Atravessada no peito, deixa as mãos livres." },
      { level: "indirect", text: "Sem ela, os bolsos da calça sofreriam." },
    ],
    tier: "B",
    station: "estante",
    region: { kind: "rect", x: 2168, y: 594, w: 96, h: 120 },
    measured: { visible: 0.99, edge: 2.25, clutter: 0.098 },
    hintRegion: "pendurada junto à estante",
    hintDirection: "à esquerda da estante, no alto",
    hintContext: "presa por uma alça comprida, num gancho",
  },
  {
    id: "gaita",
    label: "Gaita",
    accessibleLabel: "Gaita de boca",
    clues: [
      { level: "direct", text: "Toca-se soprando e puxando o ar pelos furinhos." },
      { level: "associative", text: "Cabe no bolso e tem várias casinhas de sopro." },
      { level: "associative", text: "O caubói a tocava em volta da fogueira." },
      { level: "indirect", text: "Um blues solitário cabe na palma da mão." },
      { level: "indirect", text: "Some na mão do músico, mas a canção aparece." },
    ],
    tier: "C",
    station: "estante",
    region: { kind: "rect", x: 2604, y: 1098, w: 100, h: 56 },
    measured: { visible: 0.808, edge: 1.65, clutter: 0.175 },
    hintRegion: "em cima da pilha de livros no pé da estante",
    hintDirection: "embaixo, na parte de baixo da estante, no meio",
    hintContext: "sobre livros empilhados, perto do chão",
  },
];

/** The room's look-alikes (the rules are the contract's: hidden-objects-scene.ts). */
export const SCENE_LOOKALIKES: readonly SceneLookAlike[] = [
  {
    id: "vaso-torneado",
    label: "Vaso torneado",
    resembles: "ampulheta",
    tellApart: "madeira de cintura fina, sem vidro e sem areia",
    region: { kind: "rect", x: 912, y: 892, w: 40, h: 108 },
  },
  {
    id: "tinteiros",
    label: "Tinteiros",
    resembles: "binoculo",
    tellApart: "dois frascos escuros lado a lado, sem lentes",
    region: { kind: "rect", x: 624, y: 950, w: 58, h: 50 },
  },
  {
    id: "alca-do-bau",
    label: "Alça do baú",
    resembles: "chave",
    tellApart: "um arco de latão preso à tampa, sem dentes",
    region: { kind: "rect", x: 628, y: 1258, w: 48, h: 24 },
  },
  {
    id: "fivela",
    label: "Fivela da correia",
    resembles: "chave",
    tellApart: "um aro quadrado na correia, sem haste",
    region: { kind: "rect", x: 606, y: 1386, w: 28, h: 28 },
  },
  {
    id: "carimbo",
    label: "Carimbo de lacre",
    resembles: "lupa",
    tellApart: "cabo e base de latão maciça, sem vidro",
    region: { kind: "rect", x: 1900, y: 1004, w: 46, h: 84 },
  },
  {
    id: "lata-redonda",
    label: "Lata redonda",
    resembles: "bussola",
    tellApart: "tampa lisa, sem mostrador nem agulha",
    region: { kind: "circle", cx: 1660, cy: 1206, r: 22 },
  },
  {
    id: "moedas",
    label: "Moedas",
    resembles: "relogio",
    tellApart: "discos de latão empilhados, sem mostrador nem corrente",
    region: { kind: "rect", x: 1410, y: 1180, w: 32, h: 28 },
  },
  {
    id: "chaleira",
    label: "Chaleira de latão",
    resembles: "lanterna",
    tellApart: "bico e tampa, sem vidro e sem chama",
    region: { kind: "rect", x: 2666, y: 990, w: 72, h: 70 },
  },
  {
    id: "caixinha-de-musica",
    label: "Caixinha de música",
    resembles: "camera",
    tellApart: "caixa escura com manivela, sem lente",
    region: { kind: "rect", x: 2300, y: 468, w: 110, h: 54 },
  },
  {
    id: "vaso-de-porcelana",
    label: "Vaso de porcelana",
    resembles: "estatueta",
    tellApart: "branco e liso, sem rosto e sem braços",
    region: { kind: "rect", x: 2834, y: 282, w: 40, h: 88 },
  },
  {
    id: "rolo-de-papel",
    label: "Rolo de papel",
    resembles: "estatueta",
    tellApart: "um cilindro claro em pé, sem forma de figura",
    region: { kind: "rect", x: 2540, y: 252, w: 26, h: 118 },
  },
  {
    id: "cesta-de-arame",
    label: "Cesta de arame",
    resembles: "gaiola",
    tellApart: "uma cesta aberta de arame pendurada, sem portinha e sem poleiro",
    region: { kind: "rect", x: 900, y: 220, w: 52, h: 74 },
  },
  {
    id: "roseta-entalhada",
    label: "Roseta entalhada",
    resembles: "caracol",
    tellApart: "um enfeite redondo esculpido na madeira, sem antenas e sem corpo",
    region: { kind: "rect", x: 452, y: 1066, w: 48, h: 48 },
  },
  {
    id: "peao-de-xadrez",
    label: "Peão de xadrez",
    resembles: "piao",
    tellApart: "uma peça de jogo de cabeça redonda, que não gira",
    region: { kind: "rect", x: 826, y: 1360, w: 40, h: 64 },
  },
  {
    id: "medalha",
    label: "Medalha",
    resembles: "relogio",
    tellApart: "um disco de latão com fita, sem ponteiros",
    region: { kind: "rect", x: 1176, y: 942, w: 48, h: 42 },
  },
  {
    id: "acucareiro",
    label: "Açucareiro",
    resembles: "xicara",
    tellApart: "um pote de louça com tampa e duas alcinhas, sem pires",
    region: { kind: "rect", x: 1194, y: 648, w: 48, h: 52 },
  },
  {
    id: "tampa-de-pote",
    label: "Tampa de pote",
    resembles: "bussola",
    tellApart: "um disco de latão liso, sem agulha e sem argola",
    region: { kind: "rect", x: 1180, y: 1292, w: 56, h: 40 },
  },
  {
    id: "compasso-de-pontas",
    label: "Compasso de pontas",
    resembles: "tesoura",
    tellApart: "duas hastes finas unidas por uma dobradiça, sem anéis",
    region: { kind: "rect", x: 1640, y: 1146, w: 48, h: 34 },
  },
  {
    id: "abacaxi-de-madeira",
    label: "Abacaxi de madeira",
    resembles: "pinha",
    tellApart: "um enfeite entalhado com coroa de folhas, sem escamas soltas",
    region: { kind: "rect", x: 1390, y: 600, w: 36, h: 56 },
  },
  {
    id: "folha-emoldurada",
    label: "Folha emoldurada",
    resembles: "borboleta",
    tellApart: "uma folha prensada num quadro, sem asas",
    region: { kind: "rect", x: 1950, y: 590, w: 116, h: 140 },
  },
  {
    id: "caixa-de-fosforos",
    label: "Caixa de fósforos",
    resembles: "gaita",
    tellApart: "uma caixinha de papelão com gaveta, sem furos",
    region: { kind: "rect", x: 2476, y: 1100, w: 60, h: 40 },
  },
  {
    id: "estojo-de-oculos",
    label: "Estojo de óculos",
    resembles: "gaita",
    tellApart: "um estojo fechado de couro, sem furinhos de sopro",
    region: { kind: "rect", x: 2820, y: 1094, w: 70, h: 36 },
  },
];

/**
 * Versioned folder: a new art kit is a new folder, never an overwrite (v0 was the
 * skeleton's, v1 EXPERIENCE-02's; v2 is GAME03-CALIBRATION-02A's — five new
 * objects tucked into the room and eleven more look-alikes).
 */
export const SCENE_ASSET_BASE = "/assets/hidden-objects/explorer-studio/v2";

export const SCENE_LAYERS: readonly SceneLayer[] = [
  {
    id: "back",
    src: `${SCENE_ASSET_BASE}/back.webp`,
    rect: { x: 160, y: 90, w: 920, h: 1000 },
    parallax: 0.92,
    opaque: [{ x: 160, y: 90, w: 920, h: 1000 }],
  },
  {
    id: "plate",
    src: `${SCENE_ASSET_BASE}/plate.webp`,
    rect: { x: 0, y: 0, w: SCENE_WIDTH, h: SCENE_HEIGHT },
    parallax: 1,
    opaque: [{ x: 0, y: 0, w: SCENE_WIDTH, h: SCENE_HEIGHT }],
  },
  {
    id: "front",
    src: `${SCENE_ASSET_BASE}/front.webp`,
    rect: { x: 0, y: 0, w: 360, h: SCENE_HEIGHT },
    parallax: 1.05,
    opaque: [
      { x: 0, y: 0, w: 300, h: 360 },
      { x: 0, y: 1150, w: 340, h: 450 },
    ],
  },
  {
    // GAME03-EXPERIENCE-02: the right edge gets its own foreground, so the room
    // is framed in depth on both sides — vines from the beam, books on the floor.
    id: "front-right",
    src: `${SCENE_ASSET_BASE}/front-right.webp`,
    rect: { x: 2700, y: 0, w: 500, h: SCENE_HEIGHT },
    parallax: 1.05,
    opaque: [
      { x: 2700, y: 0, w: 500, h: 156 },
      { x: 3008, y: 0, w: 192, h: 400 },
      { x: 3024, y: 1440, w: 176, h: 160 },
    ],
  },
];

export const thumbnailSrc = (id: TargetId) => `${SCENE_ASSET_BASE}/thumbs/${id}.webp`;

/** The Estúdio as the engine plays it. */
export const EXPLORER_STUDIO: SceneDefinition = {
  id: SCENE_ID,
  name: "Estúdio do Explorador",
  copy: {
    tagline: "Uma sala de viagens no fim da tarde",
    viewportLabel: "Cena do Estúdio das Descobertas",
    completeTitle: "Estúdio explorado",
    summary: "Você encontrou todos os objetos do Estúdio.",
  },
  // the intro's art (kit v1, which the platform's world visuals name): already on the device when the selector shows it
  preview: "/assets/hidden-objects/explorer-studio/v1/hero.webp",
  width: SCENE_WIDTH,
  height: SCENE_HEIGHT,
  stations: SCENE_STATIONS,
  initialStation: "mesa",
  pool: HIDDEN_OBJECTS,
  lookAlikes: SCENE_LOOKALIKES,
  layers: SCENE_LAYERS,
  thumbnail: thumbnailSrc,
  backdrop: "#120c08",
};
